name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Typecheck
        run: npm run typecheck

      - name: Test
        run: npm run test

      - name: Test Coverage
        run: npm run test:coverage

      - name: Bundle Stats
        run: npm run bundle:stats

      - name: Lint
        run: npm run lint

      - name: Format Check
        run: npm run format:check

      - name: Build Storybook (lib)
        if: github.event_name == 'push' || contains(github.event.pull_request.changed_files, 'lib/**')
        run: npm run build-storybook -w lib

      - name: Archive Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            lib/coverage
            retention-days: 7

      - name: Archive Bundle Stats
        uses: actions/upload-artifact@v4
        with:
          name: bundle-stats
          path: |
            lib/dist/stats.html
            doc-site/build/stats.html
          retention-days: 7

      - name: Archive Storybook
        uses: actions/upload-artifact@v4
        with:
          name: storybook
          path: lib/storybook-static
