name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run build, typecheck, test, coverage, bundle stats, lint, and format check
        run: npm run build && npm run typecheck && npm run test && npm run test:coverage && npm run bundle:stats && npm run lint && npm run format:check

      - name: Archive coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: lib/coverage/
          retention-days: 7

      - name: Archive bundle stats
        uses: actions/upload-artifact@v4
        with:
          name: bundle-stats
          path: lib/dist/stats.html
          retention-days: 7